# Generated by Django 4.0.3 on 2022-03-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_favorite_book_favorited_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
